In [1]:
import pandas as pd

## Task 1

In [6]:
bike_sharing = pd.read_csv('bike_sharing.csv')
print(bike_sharing.shape)
print(bike_sharing.columns.tolist())
bike_sharing.head()

(731, 16)
['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

It looks like each row is a day that shows weather and the number of people who register for the bike sharing service

In [5]:
grad = pd.read_csv('grad.csv')
print(grad.shape)
print(grad.columns.tolist())
grad.head()

(400, 4)
['admit', 'gre', 'gpa', 'rank']

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

Grad school admission and other labels

In [7]:
insurance = pd.read_csv('insurance.csv')
print(insurance.shape)
print(insurance.columns.tolist())
insurance.head()

(1338, 7)
['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

People's charges, and other life information

## Task 2

In [9]:
insurance_target = insurance['charges']
insurance_target.head(10)

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
5     3756.62160
6     8240.58960
7     7281.50560
8     6406.41070
9    28923.13692
Name: charges, dtype: float64

The target column contains the amount that each person is paying for insurance.

In [10]:
grad_target = grad['admit']
grad_target.head(10)

0    0
1    1
2    1
3    1
4    0
5    1
6    1
7    0
8    1
9    0
Name: admit, dtype: int64

Whether each person got admitted to the graduate program

In [11]:
bike_sharing_target = bike_sharing['cnt']
bike_sharing_target.head(10)

0     985
1     801
2    1349
3    1562
4    1600
5    1606
6    1510
7     959
8     822
9    1321
Name: cnt, dtype: int64

The number of total bike rentals each day

## Task 3

In [12]:
insurance_target.unique()

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603], shape=(1337,))

Insurance- regression, as it looks like the target is a continuous numeric column

In [14]:
grad_target.unique()

array([0, 1])

Grad- binary classification as we only have 2 outcomes- yes or no

In [16]:
bike_sharing_target.unique()

array([ 985,  801, 1349, 1562, 1600, 1606, 1510,  959,  822, 1321, 1263,
       1162, 1406, 1421, 1248, 1204, 1000,  683, 1650, 1927, 1543,  981,
        986, 1416, 1985,  506,  431, 1167, 1098, 1096, 1501, 1360, 1526,
       1550, 1708, 1005, 1623, 1712, 1530, 1605, 1538, 1746, 1472, 1589,
       1913, 1815, 2115, 2475, 2927, 1635, 1812, 1107, 1450, 1917, 1807,
       1461, 1969, 2402, 1446, 1851, 2134, 1685, 1944, 2077,  605, 1872,
       2133, 1891,  623, 1977, 2132, 2417, 2046, 2056, 2192, 2744, 3239,
       3117, 2471, 2703, 2121, 1865, 2210, 2496, 1693, 2028, 2425, 1536,
       2227, 2252, 3249, 3115, 1795, 2808, 3141, 1471, 2455, 2895, 3348,
       2034, 2162, 3267, 3126,  795, 3744, 3429, 3204, 3944, 4189, 1683,
       4036, 4191, 4073, 4400, 3872, 4058, 4595, 5312, 3351, 4401, 4451,
       2633, 4433, 4608, 4714, 4333, 4362, 4803, 4182, 4864, 4105, 3409,
       4553, 3958, 4123, 3855, 4575, 4917, 5805, 4660, 4274, 4492, 4978,
       4677, 4679, 4758, 4788, 4098, 3982, 3974, 4968, 5342, 4906, 4548,
       4833, 3915, 4586, 4966, 4460, 5020, 4891, 5180, 3767, 4844, 5119,
       4744, 4010, 4835, 4507, 4790, 4991, 5202, 5305, 4708, 4648, 5225,
       5515, 5362, 4649, 6043, 4665, 4629, 4592, 4040, 5336, 4881, 4086,
       4258, 4342, 5084, 5538, 5923, 5302, 4458, 4541, 4332, 3784, 3387,
       3285, 3606, 3840, 4590, 4656, 4390, 3846, 4475, 4302, 4266, 4845,
       3574, 4576, 4866, 4294, 3785, 4326, 4602, 4780, 4792, 4905, 4150,
       3820, 4338, 4725, 4694, 3805, 4153, 5191, 3873, 5895, 5130, 3542,
       4661, 1115, 4334, 4634, 5204, 5058, 5115, 4727, 4484, 4940, 2710,
       1996, 1842, 3544, 5345, 5046, 4713, 4763, 4785, 3659, 4760, 4511,
       4539, 3641, 4352, 4795, 2395, 5423, 5010, 4630, 4120, 3907, 4839,
       2429, 2918, 3570, 4456, 4826, 4765, 4985, 5409, 5511, 5117, 4563,
       2416, 2913, 3644, 5217, 5041, 4570, 4748, 2424, 4195, 4304, 4308,
       4381, 4187, 4687, 3894, 2659, 3747,  627, 3331, 3669, 4068, 4186,
       4046, 3926, 3649, 4035, 4205, 4109, 2933, 3368, 4067, 3717, 4486,
       1817, 3053, 3392, 3663, 3520, 2765, 1607, 2566, 1495, 2792, 3068,
       3071, 3867, 2914, 3613, 3727, 3940, 3614, 3485, 3811, 2594,  705,
       3322, 3620, 3190, 2743, 3310, 3523, 3740, 3709, 3577, 2739, 2431,
       3403, 3750, 2660, 2209, 1011,  754, 1317, 2302, 2423, 2999, 2485,
       2294, 1951, 2236, 2368, 3272, 4521, 3425, 2376, 3598, 2177, 4097,
       3214, 2493, 2311, 2298, 2935, 3376, 3292, 3163, 1301, 2432, 4339,
       4270, 4075, 3456, 4023, 3243, 3624, 4509, 4579, 3761, 4151, 2832,
       2947, 4375, 2802, 3830, 3831, 2169, 1529, 3422, 3922, 4169, 3005,
       4154, 4318, 2689, 3129, 3777, 4773, 5062, 3487, 2732, 3389, 4322,
       4363, 1834, 4990, 3194, 4066, 3423, 3333, 3956, 4916, 5382, 4569,
       4118, 4911, 5298, 5847, 6312, 6192, 4378, 7836, 5892, 6153, 6093,
       6230, 6871, 8362, 3372, 4996, 5558, 5102, 5698, 6133, 5459, 6235,
       6041, 5936, 6772, 6436, 6457, 6460, 6857, 5169, 5585, 5918, 4862,
       6398, 7460, 7132, 6370, 6691, 4367, 6565, 7290, 6624, 1027, 5633,
       6196, 5026, 6233, 4220, 6304, 5572, 5740, 6169, 6421, 6296, 6883,
       6359, 6273, 5728, 4717, 6572, 7030, 7429, 6118, 2843, 7424, 7384,
       7639, 8294, 7129, 4359, 6073, 5260, 6770, 6734, 6536, 6591, 5743,
       6855, 7338, 4127, 8120, 7641, 6998, 7001, 7055, 7494, 7736, 7498,
       6598, 6664, 4972, 7421, 7363, 7665, 7702, 6978, 5099, 6825, 6211,
       5905, 5823, 7458, 6891, 6779, 7442, 7335, 6879, 5463, 5687, 5531,
       6227, 6660, 7403, 6241, 6207, 4840, 4672, 6569, 6290, 7264, 7446,
       7499, 6969, 6031, 6830, 6786, 5713, 5870, 4459, 7410, 6966, 7592,
       8173, 6861, 6904, 6685, 6597, 7105, 7216, 7580, 7261, 7175, 6824,
       5464, 7013, 7273, 7534, 7286, 5786, 6299, 6544, 6784, 7347, 7605,
       7148, 7865, 4549, 6530, 7006, 7375, 7765, 7582, 6053, 5255, 6917,
       7040, 7697, 7713, 7350, 6140, 5810, 6034, 6864, 7112, 6203, 7504,
       5976, 8227, 7525, 7767, 7870, 7804, 8009, 8714, 7333, 6869, 7591,
       7720, 8167, 8395, 7907, 7436, 7538, 7733, 7393, 7415, 8555, 6889,
       6778, 4639, 7572, 7328, 8156, 7965, 3510, 5478, 6392, 7691, 7570,
       7282, 7109, 6639, 5875, 7461, 7509, 5424, 8090, 7058, 7466, 7693,
       7359, 7444, 7852,   22, 5566, 5986, 5138, 5107, 5259, 5686, 5035,
       5315, 5992, 6852, 6269, 4094, 5495, 5445, 5629, 4669, 5499, 5634,
       5146, 3910, 2277, 5087, 3959, 5323, 5668, 6234, 6606, 5729, 5375,
       5008, 5582, 3228, 5170, 5501, 5319, 5532, 5611, 5047, 3786, 4585,
       5557, 5267, 4128, 3623, 1749, 1787,  920, 1013,  441, 2114, 3095,
       1341, 1796, 2729])

Bike sharing- also regression because the target column is a continuous numeric variable